# Generated by Django 2.0.6 on 2019-06-12 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20190612_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=32)),
                ('wide', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='chasis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.Chasis'),
        ),
    ]
